#!/bin/bash

CONFIG=$HOME/.arduino15/preferences.txt

if [ "X$1" == "X" ]
then
  SKETCH=`grep last.sketch0.path $CONFIG`
  SKETCH=`dirname $SKETCH`
  SKETCH=${SKETCH/*=/}
  echo $SKETCH
else
  SKETCH=$PWD
fi

if [ -f $SKETCH/preferences.txt ]
then
  echo "Using $SKETCH/preferences.txt"
  PREF=`grep -v 'custom_\|board=' $CONFIG`
  echo "$PREF" > $CONFIG
  cat $SKETCH/preferences.txt >> $CONFIG
fi

arduino > /dev/null 2>&1

SKETCH=`grep last.sketch0.path $CONFIG`
SKETCH=`dirname $SKETCH`
SKETCH=${SKETCH/*=/}

echo "Saving preferences.txt in $SKETCH? [y/n]"
read -n 1 KEY
if [ $KEY == "y" ]
then
  grep 'custom_\|board=' $CONFIG > $SKETCH/preferences.txt
fi

